#!/usr/bin/env bash

configpath="$(dirname "$0")"

hc() {
    herbstclient "$@"
}

reset_attrs() {
	# for layout-max-toggle.sh
	hc remove_attr tmp.my_max_toggle
	hc new_attr string tmp.my_max_toggle
}

# begin
hc emit_hook reload
reset_attrs

# keybindings
hc keyunbind --all

Mod=Mod4 # Mod4=super; Mod1=alt

# hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-q close_or_remove

hc keybind $Mod-Return spawn konsole
hc keybind $Mod-Shift-Return spawn emacsclient -c
hc keybind $Mod-d spawn rofi -show drun
hc keybind $Mod-Shift-d spawn rofi -show window

# focusing clients
hc keybind $Mod-Left			focus left
hc keybind $Mod-Down			focus down
hc keybind $Mod-Up				focus up
hc keybind $Mod-Right			focus right
hc keybind $Mod-h				focus left
hc keybind $Mod-j				focus down
hc keybind $Mod-k				focus up
hc keybind $Mod-l				focus right
hc keybind $Mod-bracketleft		focus_edge -i left
hc keybind $Mod-bracketright	focus_edge -i right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left			 shift left
hc keybind $Mod-Shift-Down			 shift down
hc keybind $Mod-Shift-Up			 shift up
hc keybind $Mod-Shift-Right			 shift right
hc keybind $Mod-Shift-h				 shift left
hc keybind $Mod-Shift-j				 shift down
hc keybind $Mod-Shift-k				 shift up
hc keybind $Mod-Shift-l				 shift right
hc keybind $Mod-Shift-bracketleft	 shift_edge -i left
hc keybind $Mod-Shift-bracketright	 shift_edge -i right

# splitting frames
hc keybind $Mod-o       chain , split right 0.5 , focus right
hc keybind $Mod-u       chain , split bottom 0.5 , focus down
hc keybind $Mod-Shift-o chain , split right 0.5 , shift right
hc keybind $Mod-Shift-u chain , split bottom 0.5 , shift down
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..5} )
tag_keys=( {1..5} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible
hc keybind $Mod-slash use_previous

# temporary monitor toggle
temp_tag="temp"
temp_monitor="temp_monitor"

hc add $temp_tag
hc keybind $Mod-Shift-grave move $temp_tag

hc keybind $Mod-grave \
   or ! remove_monitor $temp_monitor \
      ! and . or , add_monitor 1280x768+100+100 $temp_tag $temp_monitor \
                 , raise_monitor $temp_monitor \
			. focus_monitor $temp_monitor

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-p pseudotile toggle

# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-v cycle_layout +1 vertical horizontal
hc keybind $Mod-space \
            or , and . compare tags.focus.curframe_wcount = 2 \
                     . cycle_layout +1 vertical horizontal max vertical grid \
               , cycle_layout +1

hc keybind $Mod-m spawn "${configpath}/herbstluftwm/layout-max-toggle.sh"

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
. "${configpath}/herbstluftwm/theme-breeze.sh"

# other binds
hc keybind $Mod-Control-Shift-b cycle_value frame_border_width 0 1 2
hc keybind $Mod-Control-Shift-r rotate

# rules
hc unrule -F
#hc rule clashcs=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
# hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
# hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|[Kk]onsole)' focus=on

hc rule class~'plasmashell' floating=on floatplacement=center
hc rule class='krunner' pseudotile=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'
hc unlock # just to be sure

# monitors
hc detect_monitors
