# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "thunderbolt" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/nixos-root";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."nixos-root".device = "/dev/disk/by-uuid/2422b034-d2f3-4206-9de0-772198d79b50";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7279-9158";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/nixos-root";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/nixos-root";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/mnt/files" =
    { device = "/dev/mapper/files";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."files".device = "/dev/disk/by-uuid/b7401f77-6f37-481b-bcfb-3539552c3fad";

  fileSystems."/mnt/media" =
    { device = "/dev/mapper/media";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."media".device = "/dev/disk/by-uuid/4a6c07dc-7930-49dd-9673-c74d073b678e";

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
